### ISSUE TITLE
Focusing & unfocusing non-empty Required TextField with Validator clears validation error

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-text-field-flow#186] opened 2019-05-24 09:32 UTC
`<vaadin.version>13.0.7</vaadin.version>`

If you create a TextField, set it required with `setRequired(true)` and bind it with a `Validator`, then the filling the Required requirement and focus + unfocus is enough to clear the validation error even though the `Validator` still fails. Test view to reproduce:
```
public class MainView extends Div {

    public static final String ERROR = "String is not 'Test'";

    public MainView() {
        TextField required = new TextField("Required");
        Binder<TestBean> testBinder = new Binder<>();
        testBinder.setBean(new TestBean());
        required.setValueChangeMode(ValueChangeMode.EAGER);
        required.setRequired(true);
        Binder.Binding<TestBean, String> requiredBinding = testBinder.forField(required)
                .withValidator((Validator<String>) (value, context) -> {
                    if ("Test".equals(value)) {
                        return ValidationResult.ok();
                    } else {
                        return ValidationResult.error(ERROR);
                    }
                }).bind(TestBean::getRequired, TestBean::setRequired);

        add(required);
        Button revalidate = new Button("Validate");
        revalidate.addClickListener(clickEvent -> {
            requiredBinding.validate();
        });
        add(revalidate);
        add(new Paragraph("1. Click 'Validate'"));
        add(new Paragraph("2. Click the TextField to focus it"));
        add(new Paragraph("3. Click outside the TextField to blur it"));
        add(new Paragraph("4. TextField should still be invalid"));
    }

    private class TestBean {
        private String required = "Not Test";
        public String getRequired() {
            return required;
        }
        public void setRequired(String required) {
            this.required = required;
        }
    }
}
```

**Comment by peholmst** [comment] 2019-06-05 12:59
Reproduced

**Comment by peholmst** [comment] 2019-06-05 13:22
The `errorMessage` property of the server-side component still remains after the text field is blurred, indicating that the bug is on the client side.

**Comment by peholmst** [comment] 2019-06-06 12:41
The problem is that the client side text field will re-run the validation every time the field is blurred. Since this validation error is set on the server side, the client side validation will pass and clear the invalid flag.

**Comment by peholmst** [comment] 2019-06-06 13:37
Turns out this is in fact a duplicate of #134 . If the call to `setRequired` is replaced with `setRequiredIndicatorVisible`, the test view works as expected.

**Closed by peholmst** 2019-06-06 13:37 UTC
Labels: BFP, bug
