### ISSUE TITLE
Email field in RTL must be from left to right

### ISSUE THREAD

**Issue by shadikhani** [vaadin/vaadin-text-field-flow#303] opened 2020-04-20 12:42 UTC
Values in Email field should be entered from left to right.

**Comment by alvarezguille** [comment] 2020-04-22 07:09
Thanks for the issue, we'll work on it as part of https://github.com/vaadin/vaadin-text-field/issues/466

Closing as duplicate of https://github.com/vaadin/vaadin-text-field/issues/466

**Closed by alvarezguille** 2020-04-22 07:09 UTC
