### ISSUE TITLE
TextArea does not show scrollbar when opening with overflowing text

### ISSUE THREAD

**Issue by campbellbartlett** [vaadin/vaadin-text-field-flow#132] opened 2019-01-24 03:32 UTC
Hi,
In our project we have a button that shows a dialog that contains a text area. The user modifies the text in the text area then closes the dialog.
If the user wants to make more changes, they open the dialog again.
We have found that when the user opens the dialog and the text area is overflowing, the scrollbar does not show.
If the user modifies the text by adding or removing a line, the scrollbar shows.
Here is a [demo](https://i.imgur.com/nw6InZJ.gif)
Here is how we create the text area in the constructor for the dialog:
```
MyDialog() {
Textarea textArea = new Textarea();
...create save and cancel buttons...
this.add(textArea, buttons);
textArea.setHeight("80vh");
textArea.setWidth("75vw");
}
```

The dialog is constructed once and then _open()_ and _close()_ is used when showing and hiding the dialog.
We set the value for the Textarea using _Textarea.setValue()_

Is this a bug or is there another way to show the scrollbar? Ideally it would always be shown - this text area is for our users to input lots of text so will almost always involve scrolling of some kind.

**Comment by LennartKuell** [comment] 2019-03-07 11:13
I'm having the same problem: The Scrollbar won't appear until I edit the TextArea, if the TextArea is inside a Dialog. If the TextArea is outside a Dialog, the Scrollbar is shown from the beginning and everything works fine.
Our TextArea is supposed to be read-only and the scrollbar should always be displayed, if there is overflowing text, so we can't make the Scrollbar appear by editing. I tested this with Vaadin 12.0.3 and vaadin-text-field-flow 1.2.1 and 1.3.0.

Source code to reproduce:
```java
@Route("text-area-scroll")
public class TextAreaScroll extends Div {

  public TextAreaScroll() {
    add(new Button("Show Dialog", e -> {
      TextArea textArea = new TextArea();
      textArea.setValue("Test\nTest\nTest\nTest\nTest\nTest\nTest\nTest\nTest\nTest\nTest\nTest\nTest\nTest\nTest\nTest\nTest");
      textArea.setHeight("100px");
      textArea.setWidth("30vw");

      new Dialog(textArea).open();
    }));
  }
}
```

**Comment by campbellbartlett** [comment] 2019-03-07 21:27
Hi @LennartKuell ,
We are now using the [ace-editor](https://vaadin.com/directory/component/juicyjuicy-ace-editor)  component which handles the read-only and scrolling better. It is also better in our case as we are using the text area to show javascript and the ace-editor adds syntax highlighting. Hopefully it might suit your case as well.

**Comment by web-padawan** [comment] 2020-02-17 17:57
Appears to be a duplicate of vaadin/vaadin-text-field#409

**Closed by web-padawan** 2020-02-17 17:57 UTC
