### ISSUE TITLE
NumberField setValue() Rounding up Numbers

### ISSUE THREAD

**Issue by roomtek** [vaadin/vaadin-text-field-flow#147] opened 2019-02-24 05:42 UTC
The NumberField always rounds up the value set with setValue();

so a 9.99 from the server shows up as 10.00 on the UI: 
		 
		NumberField unitprice = new NumberField("Unit Price");
		unitprice.setMin(0);
		unitprice.setStep(0.01);
		unitprice.getElement().setAttribute("colspan", "4");
		unitprice.setPrefixComponent(new Span("$")); 
		unitprice.setValue(9.99); 

![image](https://user-images.githubusercontent.com/528961/53295613-07313700-37cd-11e9-9b1b-3b482729aa7a.png)

**Comment by alvarezguille** [comment] 2019-02-26 08:27
Related to vaadin/vaadin-text-field#331

**Comment by tomivirkki** [comment] 2019-03-04 09:24
Closing as a dupe of https://github.com/vaadin/vaadin-text-field/issues/331

**Closed by tomivirkki** 2019-03-04 09:24 UTC
Labels: Components, bug, issue-backlog
