### ISSUE TITLE
Field not set invalid if binder is validated

### ISSUE THREAD

**Issue by MartinSoftwareSchreiber** [vaadin/vaadin-text-field-flow#271] opened 2019-12-03 16:14 UTC
### Description
If I have a Binder with mandatory fields, no error is shown if the validation of the binder is not successful.

### Expected outcome
The field shows the error from the Binder.

### Actual outcome
Nothing is shown on the field.
I have to manually set the field invalid to make it work (commented code).

### Steps to reproduce
Use this simple view and check the submit. After submit I would expect to see the field that has an error.
```java
@Route("test")
public class TestView  extends Div {

    private String value;

    public TestView() {
        TextField field = new TextField("Mandatory field:");
        field.setRequired(true);
        field.setRequiredIndicatorVisible(true);
        Binder<TestView> binder = new Binder();
        binder.setBean(this);
        binder.forField(field).asRequired("Required")
                .bind(TestView::getValue, TestView::setValue);

        add(field);

        Button submit = new Button("Submit");
        submit.addClickListener(e -> {
            // workaround to mark field invalid
            //binder.validate().getFieldValidationErrors()
            //        .forEach(t -> ((HasValidation)t.getField()).setInvalid(true));
            if(!binder.isValid()) {
                Notification.show("Error");
                return;
            }
            Notification.show("Success");
        });
        add(submit);
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
```

### Browsers Affected
Only Chrome and edge checked but I assume all browsers are affected.

**Comment by web-padawan** [comment] 2019-12-03 16:46
Please don't use `setRequired` with Binder. This method will be deprecated in #134 

This is also duplicate of #186

**Comment by tomivirkki** [comment] 2019-12-04 08:00
@MartinSoftwareSchreiber which Vaadin version do you use? This issue is already fixed in `14.0.15`
(and `14.1.0.rc1`)

**Comment by MartinSoftwareSchreiber** [comment] 2019-12-04 08:22
Currently 14.0.14 but I'll update asap.

**Comment by MartinSoftwareSchreiber** [comment] 2019-12-04 09:09
Doesn't look like it's fixed with 14.0.15. Same behaviour, regardless if the textfield itself is set to required or not.

**Comment by tomivirkki** [comment] 2019-12-04 09:12
Ah, the validation logic was fixed in the release but the field isn't marked invalid indeed. Sorry about the confusion. Reopening.

**Comment by MartinSoftwareSchreiber** [comment] 2019-12-04 09:22
Ok, got it: binder.validate().isOk() is what I expect, binder.isValid() behaves differently.

**Comment by tomivirkki** [comment] 2019-12-04 09:26
True, `binder.isValid()` actually documents this `Note: Calling this method will not trigger status change events, unlike validate() and will not modify the UI. To also update error indicators on fields, use validate().isOk().`

**Closed by tomivirkki** 2019-12-04 09:26 UTC

**Comment by MartinSoftwareSchreiber** [comment] 2019-12-04 09:32
True, says so clearly. Thanks.
