### ISSUE TITLE
Field value gets lost if the user is quick

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-text-field-flow#231] opened 2019-10-02 13:52 UTC
In a scenario like this:

```java
var field = new TextField();
var button = new Button();
Shortcuts.addShortcutListener(field, button::click, Key.ENTER);
```

If the user writes in the field and press <kbd>ENTER</kbd>, the button click listener will find an empty `field.getValue()`.

I guess this is because of field updates being sent lazily, which is good (can't make it eager if there are many and they's server-side validation). Anyway, there must be a way to flush all pending changed values to the server before triggering the click action, e.g.

```java
var field = new TextField();
var button = new Button();
Shortcuts.addShortcutListener(field, () -> {
    field.flush();
    button.click();
}, Key.ENTER);
```

**Comment by PatrickBellositz** [comment] 2020-09-15 07:14
I find that even if you do set the TextField to ValueChangeMode.EAGER, if you are quick enough only parts of your input may be recognized, while waiting a bit longer will detect the full contents.

**Comment by yuriy-fix** [comment] 2020-09-23 09:42
Dear @heruan, in the first example the way to fix it would be to use `allowBrowserDefault()` on `addShortcutListener`. Otherwise it will `preventDefault` on <kbd>Enter</kbd> `keydown` and `change` event won't occur on native input internally.

```java
TextField field = new TextField();
Button button = new Button("Check value");
Div valueBlock = new Div();
Shortcuts.addShortcutListener(field, button::click, Key.ENTER).allowBrowserDefault();

button.addClickListener(e -> valueBlock.setText(field.getValue()));
```
Note: In this example you can also get the value before clickListener in shortcutListener.
I have created a ticket that could help avoiding this issue in future: https://github.com/vaadin/flow/issues/9053

As for the second example with blurring the field. `button.click()` will trigger server-side event, so `blur()` for the field will be executed within the next roundtrip, however `click()` will occur immediately. The way to solve that is to use `clickInClient()`, so that both will occur on client.

```java
TextField field = new TextField();
field.setValueChangeMode(ValueChangeMode.ON_BLUR);

Button button = new Button("Check value");
Div valueBlock = new Div();

Shortcuts.addShortcutListener(field, e -> {
  field.blur();
  button.clickInClient();
}, Key.ENTER);

button.addClickListener(e -> valueBlock.setText(field.getValue()));
```

**Comment by yuriy-fix** [comment] 2020-09-23 09:42
Dear @PatrickBellositz , the delay can be caused by the client-server synchronization logic. Cannot say exactly what is the problem. Could you please provide a code sample to reproduce the issue that you are facing?

**Comment by PatrickBellositz** [comment] 2020-09-23 11:38
Upon reading your reply and further inspection I found an error in my logic. Thank you for your time.

**Comment by yuriy-fix** [comment] 2020-09-24 07:22
Closed in favour of https://github.com/vaadin/flow/issues/9053.

**Closed by yuriy-fix** 2020-09-24 07:22 UTC
