### ISSUE TITLE
Some text removed when lazy value change mode activated

### ISSUE THREAD

**Issue by steffen-harbich-itc** [vaadin/vaadin-text-field-flow#209] opened 2019-07-10 10:20 UTC
I have a simple text field with lazy change mode:

```
    TextField inputField = new TextField();
    inputField.setValueChangeMode(ValueChangeMode.LAZY);
    inputField.setValueChangeTimeout(500);
    ...
```
The text field has a value change listener that updates a Grid using the value of the text field as filter. Sometimes when I enter text then some of the first entered characters are removed. See this screen capture: 
![vaadinbug](https://user-images.githubusercontent.com/19586082/60961140-c402db00-a30b-11e9-8b0c-36b22faa8ebc.gif)
The text "lucy" was entered but when the Grid is refreshed in between, the text changes to "luy", i.e. the "c" was swallowed. Unfortunately, it is not easy to reproduce. Should be

There is no "inputField.setValue" call in my code, so I think this is a bug with the lazy value change mode?

Settings:
Vaadin 14 rc4, JDK 11, Windows, Firefox & Chrome

**Comment by ttsanton** [comment] 2019-09-16 12:46
I am also encountering this problem - agreed that it doesn't happen consistently, but characters mysteriously get deleted while being entered in both TextFields and TextAreas.

My set up for text fields are similar to @steffen-harbich-itc, although I do not use the call to `.setValueChangeTimeout()` and the components are bound to a Binder with basic validation such as `.setRequired()` or `.withValidator(new StringLengthValidator(...))`

**Comment by steffen-harbich-itc** [comment] 2019-11-24 07:25
My observation is that this happens almost consistently when you have a lazy-mode filter text field and a grid that reacts on that filter. Typing just in the moment when the grid is refreshing its data (which lasts some seconds in my case) will swallow letters. I will try to make an example for project.

**Comment by steffen-harbich-itc** [comment] 2019-11-24 08:17
I was able to reproduce the issue in a simple example project:
[lazy-swallow-letters.zip](https://github.com/vaadin/vaadin-text-field-flow/files/3883339/lazy-swallow-letters.zip)

Reproduction:

1. Start project with spring-boot:run goal
2. open localhost:8080
3. Start typing as in following screen capture ("item2" one letter after another with short delays):
![lazy-swallow-letters](https://user-images.githubusercontent.com/19586082/69491840-126bdd00-0e9b-11ea-83c7-5e7a4dabfd45.gif)

As you can see the "m" is swallowed/disappearing.

**Comment by rolfwoll** [comment] 2019-12-02 12:59
FYI.

We also have this problem in our project which in practice prevents us from using lazy mode for validation.

**Comment by tulioag** [comment] 2019-12-11 09:02
Created issue https://github.com/vaadin/flow/issues/7128 in Flow since it can also be reproduced in a native input.

**Comment by tulioag** [comment] 2019-12-11 13:18
Closing since it is a Flow issue.

**Closed by tulioag** 2019-12-11 13:18 UTC
Labels: BFP
