### ISSUE TITLE
Height problem when used with other components with validation error

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/vaadin-text-field-flow#126] opened 2018-12-28 19:41 UTC
Vaadin Platform Version: 12.0.3
If we put together a `TextField` and other components with a validation error inside `HorizontalLayout`, then the `TextField` grows vertically, as shown in this picture:
![textfieldheightproblem](https://user-images.githubusercontent.com/28312758/50526196-3e31e780-0abf-11e9-87bc-d7d50aa876dc.png)
The code for reproducing this issue is this:

```
public class MainView extends VerticalLayout {

    public MainView() {
    	HorizontalLayout hl = new HorizontalLayout();
    	ComboBox<String> cb1 = new ComboBox<>("My combobox 1", "Option 1", "Option 2", "Option 3");
    	TextField tf1 = new TextField("TextField 1");
    	ComboBox<String> cb2 = new ComboBox<>("My combobox 2", "Option 1", "Option 2", "Option 3");
    	TextField tf2 = new TextField("TextField 2");
    	hl.add(cb1,tf1,cb2,tf2);
    	this.add(hl);    	
    	cb2.setErrorMessage("A given error message");
    	cb2.setInvalid(true);
    	cb2.setRequiredIndicatorVisible(true);
    }
}

```

**Comment by web-padawan** [comment] 2018-12-28 21:12
Thanks for the issue. This is actually a duplicate of vaadin/vaadin-ordered-layout#68 and can be workarounds using CSS `align-self: baseline;` for the text-field.

We first did that in the vaadin/vaadin-text-field#248 but had to revert that change, as it was breaking other use cases. So the issue should be fixed in horizontal layout.

Closing this as a duplicate.

**Closed by web-padawan** 2018-12-28 21:12 UTC
