### ISSUE TITLE
TextField should have LAZY value change mode

### ISSUE THREAD

**Issue by mstahv** [vaadin/vaadin-text-field-flow#114] opened 2018-10-17 08:34 UTC
In previous versions we had value change mode LAZY (or similar alternative API). This feature is basic requirement for decently working form validation and filtering views.

Thus we should have LAZY mode re-introduced or similar EASY API to get similar funtionality done.

**Comment by kumm** [comment] 2018-10-23 15:03
My first approach is to introduce a new timeout property in the polymer component, and create a timer on user input. The timeout handler emits a `change` event if the value changed.
Diff can be found here [here](https://github.com/vaadin/vaadin-text-field/compare/master...kumm:to-upstream/lazy).
After `polymer serve` demo is at `http://127.0.0.1:8081/components/vaadin-text-field/demo/#text-field-change-demos`.

The delegation of the new property, and a demo are created for `TextField`. Diff can be found [here](https://github.com/vaadin/vaadin-text-field-flow/compare/master...kumm:to-upstream/lazy).
Note, the webjar is not published, so you can't compile my branch until you install one locally.
A running demo can be found [here](http://demo.webstar.hu/vaadin-text-field-flow-lazy/vaadin-text-field).

Would this approach be acceptable?

**Comment by mstahv** [comment] 2018-10-27 17:28
Awesome @kumm! Really a long waited enhancement.

@pleku, @Legioth, @tomivirkki  or somebody else, please give preliminary look at the proposed changes so we can finally get this in.

**Comment by mstahv** [comment] 2018-10-27 17:30
As Vaadin 12 still needs a lot of testing anyways (we saw some nasty issues at CodeOne, @pleku knows about those). maybe we could get this still into that?

**Comment by mstahv** [comment] 2018-10-29 15:56
I checked the code again with less jetlagged eyes, I think we should also provide a decent default value for the commitTimeout, for the flexible API proposed by @kumm. So either a LAZY mode or having the well-thought timeout somewhere as a constant. It is very good to have that adjustable, but we shouldn't force each and every user find out a good default for it. In the past (years ago) I spent quite a lot of time to figure out a proper default, I think that can be found out from our older products.

**Comment by pleku** [comment] 2018-10-30 14:52
@kumm please make a PR so the team can already start the review process. You can mark it as "WIP" in the PR title for now so nobody will merge it before it is ready.

I agree with the comment made by @mstahv though. The previously used default timeout has been 400ms https://github.com/vaadin/framework/blob/dee4a2caa80066bcdd031ec445c8bf80ba313ab9/shared/src/main/java/com/vaadin/shared/ui/textfield/AbstractTextFieldState.java#L53

**Comment by kumm** [comment] 2018-10-30 17:41
I would define the constant on client side as `commitTimeout` property default value. This way a new boolean property is needed to activate this change event emitting mode something like `commitOnTimeout`.
Ok, I will send a PR for the webcomponent ( vaadin-text-field ) project first.

**Comment by pekam** [comment] 2018-11-07 13:03
The proper way to fix this is to add the `LAZY` value to `ValueChangeMode` enum in https://github.com/vaadin/flow and make it work for all the components that implement `HasValueChangeMode` mixin interface. Adding `ValueChangeMode.LAZY` to Flow and implementing the debouncer only for TextField would mean that we have broken API for any other `HasValueChangeMode` component.

Currently the `ValueChangeMode` is used just to decide [which client-side event will trigger the server-side `ValueChangeEvent`](https://github.com/vaadin/flow/blob/3145be0c61b95629c0c512be565d8ab6212f2c1c/flow-data/src/main/java/com/vaadin/flow/data/value/ValueChangeMode.java#L76). The logic in `AbstractSinglePropertyField` and related classes should be extended so that in the case of `ValueChangeMode.LAZY`, it should use the same client-side event as `ValueChangeMode.EAGER`, but also add a debouncer on it. This way it should work for all the components by delaying their `EAGER` value changes.

Even though Flow has Java API for debouncing client-side events with `Element::addEventListener`, the problem is that `Element::synchronizeProperty`, which is used by `AbstractSinglePropertyField`, doesn't have the debounce feature. According to @Legioth it may also be quite tricky to implement.

@kumm, you have added debouncing API for the web component, but we have concluded it's not something that we want to include. For frontend-developers debouncing is an easy task anyway without a need for a helper API in the web component. If we add this kind of special treatment just for TextField, it should be for the Flow component only. We can inject custom JavaScript functionality just for the Flow component similarly to what we have for ComboBox ([comboBoxConnector.js](https://github.com/vaadin/vaadin-combo-box-flow/blob/master/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js)), Grid and some others.

So we have a few options on how to proceed:
1. Add `ValueChangeMode.LAZY` to Flow and implement debouncing for `Element::synchronizeProperty` so that the mode works out-of-the-box for all components. This would be the best option in the long run, but it is hard and requires knowledge of Flow internals.
2. Add `ValueChangeMode.LAZY` to Flow and require each `HasValueChangeMode` component to implement support for it. Then we could add a JavaScript connector for TextField. It would be also possible to later change the implementation to option 1 without introducing API breaking changes. Also, I'm not sure how many components we currently have that implement `HasValueChangeMode`. Maybe this repository contains all of them? In that case this is not a bad option.
3. Instead of adding `ValueChangeMode.LAZY`, add some other debouncing API just for TextField. Then the API would be different from V8 and it would be useless if/when we later implement the `ValueChangeMode` properly.

**Comment by kumm** [comment] 2018-11-07 19:18
Thanks for the pointers!
The first thing I expelled is changing synchronization and debounce on server side, and tried the easy way instead.
I guess ( and according to V8 ) this change mode is useful for components with text input, so this repository should be the right place.

A JS connector is definitely a better idea than my hard coupled implementation. 
I'm going to try this way. The component API is the next step - preferably with `ValueChangeMode.LAZY` -.

**Comment by pekam** [comment] 2018-11-08 07:33
Yeah, feels like option 2 is the way to go.

So you need to make a PR to Flow for adding `ValueChangeMode.LAZY`, and then handle the lazy case separately in [here](https://github.com/vaadin/vaadin-text-field-flow/blob/54292726f10a0e44d35eef33db1aaf6f709ac791/src/main/java/com/vaadin/flow/component/textfield/TextField.java#L157), for example by invoking a JavaScript function that is defined in a JS connector. Also do the same for TextArea and PasswordField.

It's hard to check which components implement `HasValueChangeMode` because each of them is in their own repository, but based on checking the class-hierarchy in V8, RichTextArea should be the only one besides the three in this repository. We have RichTextEditor for Flow in alpha phase currently, and we can handle that case separately.

One more tip: Polymer library contains a helper for debouncing. You can see an example how it's used for debouncing the server callbacks when users type into ComboBox filtering field [here](https://github.com/vaadin/vaadin-combo-box-flow/blob/7629b7a97dd5caa5673d029fe41edccaa49dc439/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js#L45). You can check if it could simplify the code or not.

Anyway, thanks for working on this and don't hesitate to ask any questions. :)

**Comment by Legioth** [comment] 2018-11-08 08:00
I actually got an idea for how to quite easily implement debounce support for the generic property synchronization functionality. I'll write up a separate Flow ticket about that as soon as I have time.

**Comment by kumm** [comment] 2018-11-08 22:17
Ok, until the ticket is created I play with this option 2. 
I guess [RequiredValidationUtil.java](https://github.com/vaadin/vaadin-text-field-flow/blob/master/src/main/java/com/vaadin/flow/component/textfield/RequiredValidationUtil.java) should be refactored if I introduce an other connector.
Waiting with any PR's until the preferred solution is decided.

**Comment by Legioth** [comment] 2018-11-11 20:30
There's now a Flow PR that adds a way of debouncing (or filtering) the primitive property syhchronization mechanism: https://github.com/vaadin/flow/pull/4773.

It should hopefully be quite straightforward to change `AbstractSinglePropertyField` to give access to that new API and through that also quite easily add for generic support for `ValueChangeMode.LAZY`.

**Comment by kumm** [comment] 2018-11-11 21:15
So I think option 1 is preferred now ( more universal, with the price of many server roundtrip ).
Should I start with `AbstractSinglePropertyField` or it is to be handled internally?

Just for the records meanwhile I have option 2.
flow ValueChangeMode API: https://github.com/kumm/flow/commit/b1aa3f324c7d00c89cb25dfbca124b8afe80156b
text-field with JS connector: https://github.com/kumm/vaadin-text-field-flow/commit/833d13af2a6d90f3ae8f297aebd6843a343bbe82
An updated demo can be found [here](http://demo.webstar.hu/vaadin-text-field-flow-lazy/vaadin-text-field).

**Comment by Legioth** [comment] 2018-11-11 21:29
The low-level framework changes to enable debouncing property synchronization should prevent any additional server roundtrips other than in situations where the property should actually synchronize, so option 1 shouldn't have any extra overhead compared to less generic approaches.

Feel free to continue working on the higher-level features if you're interested.

**Comment by kumm** [comment] 2018-11-12 21:42
I see, I've totally misunderstood option 1 as debouncing on event of `EAGER`.
Do not have to worry about server roundtrips.
Currently I think the starting point is to develop some way using `Element#addPropertyChangeListener(String, String, PropertyChangeListener)` from `AbstractSinglePropertyField` in a backward compatible way where `setSynchronizedEvent` have to remain.

**Comment by Legioth** [comment] 2018-11-20 11:39
Can probably be implemented so that any call to `setSynchronizedEvent` clears the previous listener registration and creates a new one based on the most recent settings?

**Comment by Legioth** [comment] 2018-11-23 11:19
That looks like a good approach for implementing the high-level functionality.

It would be great to add a getter for the debounce timeout to `DomListenerRegistration`, even though it would have to be done with a dummy `default` method in the interface as well to avoid theoretically breaking backwards compatibility. Alternatively, the implementation class could be left as package protected "for testing purposes" and then the test could get the settings directly from there.

**Comment by kumm** [comment] 2018-11-25 21:15
As far as I see `AbstractSinglePropertyFieldTest` and `ValueChangeModeTest` requires getter for debounce timeout, debounce phases, and event type. These can be useful maybe for production code too, going to extend the interface with dummy defaults.
For now tests run with mockito, and a few changes here and there.  https://github.com/kumm/flow/commit/007fe003ae6615aa31f696944e80c7fc2ced8d2f

**Comment by Legioth** [comment] 2019-01-07 07:34
#4773 was now finally merged, so there will really soon be a SNAPSHOT build of Flow to use as the foundation for this functionality.

**Comment by kumm** [comment] 2019-01-09 19:53
https://github.com/vaadin/flow/pull/4945 is sent. A V8 like API based on merged core functionality.

**Closed** 2019-03-21 08:12 UTC
Labels: enhancement

**Comment by johndevs** [comment] 2019-05-20 06:32
Great stuff! Thanks @kumm for implementing this :)

**Comment by steffen-harbich-itc** [comment] 2019-09-10 09:07
The lazy value change mode is a great feature. However, I wonder about the following scenario. 

Imagine a TextField with lazy value change mode enabled to input some user data and a "Next" button that processes the data. Now when the user is fast enough to click the button after text input then the last entered value in TextField is not applied to the server-side component, thus the button click event listener is working on outdated user input.

Wouldn't it make sense to listen on the TextField input element focus leave event on the client-side component to intercept the lazy delay in that case? I mean on blur the lazy delay could be canceled and the value change event triggered immediately (which would apply the value to the TextField before the button click event triggers).

**Comment by Legioth** [comment] 2019-12-13 09:37
@steffen-harbich-itc That is a valid concern. I would expect it to be fixed by https://github.com/vaadin/flow/pull/7154 once it gets merged and included in a release.
