### ISSUE TITLE
Feature request - Placeholder visible while typing

### ISSUE THREAD

**Issue by masbaehr** [vaadin/vaadin-text-field-flow#146] opened 2019-02-22 10:34 UTC
I was looking for a way to keep the placeholder visible so the user knows how to input something, as typing will remove any hint:

Example:
![image](https://user-images.githubusercontent.com/38694044/53236930-bcf96a00-3695-11e9-8a87-3424629ab7bf.png)

**Comment by OlliTietavainenVaadin** [comment] 2019-08-08 06:42
Also known as "masked input"

**Comment by web-padawan** [comment] 2020-02-13 20:23
Closing as duplicate of vaadin/vaadin-text-field#408 which is a feature request for masked input.

**Closed by web-padawan** 2020-02-13 20:23 UTC
Labels: Components, enhancement
